/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import General.Configuration;
import General.Nimbus;
import db.Dbcon;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithinpv
 */
public class EncryptHistory extends javax.swing.JFrame {

    int history_id;
    File outputCipherFile;

    /**
     * Creates new form EncryptHistory
     */
    public EncryptHistory() {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        loadIcons();
        send_button.setEnabled(false);
        Configuration.setIconOnLabel("binary.jpg", main_label);
    }

    private void loadIcons() {
        Configuration.setIconOnLabel("Untitled-2.png", jLabel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        send_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        encypt_size_text = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hidden_data_text = new javax.swing.JRadioButton();
        hidden_data_file = new javax.swing.JRadioButton();
        main_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Previous Encrypted Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 33, 159, -1));

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 53, 49, 49));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 123, 40, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cover file ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 168, 84, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EncryptSize");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 219, 84, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Algorithm");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 265, 84, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 307, 84, -1));

        send_button.setText("SEND");
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(send_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 504, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "ALGORITHM", "DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 79, 325, 398));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 120, 220, -1));

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 165, 220, -1));

        encypt_size_text.setEditable(false);
        getContentPane().add(encypt_size_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 216, 220, -1));

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 262, 220, -1));

        jPasswordField1.setEditable(false);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 304, 220, -1));

        jButton4.setText("show password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 342, 125, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 343, 125, -1));

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 504, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hidden data ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 387, -1, -1));

        buttonGroup1.add(hidden_data_text);
        hidden_data_text.setForeground(new java.awt.Color(255, 255, 255));
        hidden_data_text.setSelected(true);
        hidden_data_text.setText("Text");
        hidden_data_text.setEnabled(false);
        getContentPane().add(hidden_data_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 383, 61, -1));

        buttonGroup1.add(hidden_data_file);
        hidden_data_file.setForeground(new java.awt.Color(255, 255, 255));
        hidden_data_file.setText("File");
        hidden_data_file.setEnabled(false);
        getContentPane().add(hidden_data_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 383, 58, -1));

        main_label.setText("jLabel9");
        getContentPane().add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 730, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Sending sending = new Sending(history_id, outputCipherFile);
        int encryptionDataType = 0;
        if (hidden_data_file.isSelected()) {
            encryptionDataType = 1;
        }
        InputContent.encryptionDataType = encryptionDataType;
        sending.setVisible(true);

    }//GEN-LAST:event_send_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Dbcon dbcon = new Dbcon();
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        try {

            ResultSet rs = dbcon.select("select * from tbl_file_process_history order by history_id asc");
            while (rs.next()) {
                String algo = rs.getString(5);
                int algorithm = Integer.parseInt(algo);
                if (algo.equals("1")) {
                    algo = "DES";
                } else if (algo.equals("2")) {
                    algo = "TDES";
                } else {
                    algo = "RSA";
                }
                String enc_date = rs.getString("file_processed_date");
                long date2;
                try {
                    date2 = Long.parseLong(enc_date);   
                } catch (Exception e) {
                    date2 = System.currentTimeMillis();
                }
                Date date3 = new Date(date2);
                String date = date3.toString();

                dt.addRow(new String[]{rs.getString(1), rs.getString(8), algo, date});
            }
            jTable1.setModel(dt);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        Dbcon dbcon = new Dbcon();
        ResultSet rs = dbcon.select("select * from tbl_file_process_history where history_id='" + id + "'");
        try {
            if (rs.next()) {
                String name = rs.getString("cipher_file_name");
                jTextField1.setText(name);
                String size = rs.getString(7);
                jTextField2.setText(size);
                String algo = rs.getString(6);
                int algorithm_id = Integer.parseInt(algo);
                if (algorithm_id == 1) {
                    algo = "DES";
                } else if (algorithm_id == 2) {
                    algo = "TDES";
                } else {
                    algo = "RSA";
                }
                jTextField4.setText(algo);
                String password = rs.getString(4);
                jPasswordField1.setText(password);
                encypt_size_text.setText(rs.getString("cipher_file_size") + " Kb");
                jTextField5.setText("");
                String encryption_file_type = rs.getString("encryption_file_type");
                if (encryption_file_type.equals("0")) {
                    hidden_data_text.setSelected(true);
                } else {
                    hidden_data_file.setSelected(true);
                }
                outputCipherFile = new File(Configuration.videoPool + name);
                send_button.setEnabled(true);
                Configuration.setDefaultFileIcon(outputCipherFile, jLabel2);
                history_id = Integer.parseInt(id.trim());
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        Dbcon dbcon = new Dbcon();
        ResultSet rs = dbcon.select("select * from tbl_file_process_history where history_id='" + id + "'");
        try {
            if (rs.next()) {
                String password = rs.getString(4);
                jTextField5.setText(password);
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncryptHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncryptHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncryptHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EncryptHistory().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField encypt_size_text;
    private javax.swing.JRadioButton hidden_data_file;
    private javax.swing.JRadioButton hidden_data_text;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel main_label;
    private javax.swing.JButton send_button;
    // End of variables declaration//GEN-END:variables
}
