/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import General.Configuration;
import General.Nimbus;
import db.Dbcon;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author Jithinpv
 */
public class Receiving extends javax.swing.JFrame {

    File fileToBeDecrypted;
    int encryption_file_type;

    /**
     * Creates new form Receiving
     */
    public Receiving() {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Receiving(File fileToBeDecrypted, int encryption_file_type) {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        this.fileToBeDecrypted = fileToBeDecrypted;
        this.encryption_file_type = encryption_file_type;
        loadFileDetails();
        Configuration.setIconOnLabel("binary.jpg", main_label);
    }

    private void loadFileDetails() {
        if (fileToBeDecrypted != null) {
            System.out.println(fileToBeDecrypted.getName());
            file_name_label.setText(fileToBeDecrypted.getName());
            file_size_label.setText(fileToBeDecrypted.length() + " Kb");
            file_extension_label.setText(FilenameUtils.getExtension(fileToBeDecrypted.getPath()));
        } else {
            JOptionPane.showMessageDialog(rootPane, "File could not be found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        des_button = new javax.swing.JRadioButton();
        tripple_des_button = new javax.swing.JRadioButton();
        rsa_button = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        file_name_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        file_size_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        file_extension_label = new javax.swing.JLabel();
        main_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Algorithm");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 157, 163, -1));

        buttonGroup1.add(des_button);
        des_button.setForeground(new java.awt.Color(255, 255, 255));
        des_button.setSelected(true);
        des_button.setText("DES");
        getContentPane().add(des_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 189, -1, -1));

        buttonGroup1.add(tripple_des_button);
        tripple_des_button.setForeground(new java.awt.Color(255, 255, 255));
        tripple_des_button.setText("TDES");
        getContentPane().add(tripple_des_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 189, -1, -1));

        buttonGroup1.add(rsa_button);
        rsa_button.setForeground(new java.awt.Color(255, 255, 255));
        rsa_button.setText("RSA");
        getContentPane().add(rsa_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 189, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 250, 109, -1));
        getContentPane().add(password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 250, 130, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 307, 69, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 307, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("File to be decrypted");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, 145, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 481, 10));

        file_name_label.setForeground(new java.awt.Color(255, 255, 255));
        file_name_label.setText("File name");
        getContentPane().add(file_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 19, 279, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("File size");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 51, 145, -1));

        file_size_label.setForeground(new java.awt.Color(255, 255, 255));
        file_size_label.setText("0 Kb");
        getContentPane().add(file_size_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 47, 279, 22));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("File extension");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 79, 145, -1));

        file_extension_label.setForeground(new java.awt.Color(255, 255, 255));
        file_extension_label.setText("mp4");
        getContentPane().add(file_extension_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 75, 279, 22));

        main_label.setText("jLabel4");
        getContentPane().add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String password = new String(password_text.getPassword());
        if (password.equals("") || password.length() < 8) {
            JOptionPane.showMessageDialog(rootPane, "Password must be greater than or equal to 8");
        } else {

            int encryption_algorithm_id = 1;
            if (tripple_des_button.isSelected()) {
                encryption_algorithm_id = 2;
            } else if (rsa_button.isSelected()) {
                encryption_algorithm_id = 3;
            } else if (des_button.isSelected()) {
                encryption_algorithm_id = 1;
            }
            System.out.println("encryption_algorithm_id " + encryption_algorithm_id);

            this.dispose();
            Decrypt decrypt = new Decrypt(fileToBeDecrypted, encryption_file_type, password, encryption_algorithm_id);
            decrypt.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ReceiveHistory receiveHistory = new ReceiveHistory();
        receiveHistory.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Receiving().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton des_button;
    private javax.swing.JLabel file_extension_label;
    private javax.swing.JLabel file_name_label;
    private javax.swing.JLabel file_size_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel main_label;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JRadioButton rsa_button;
    private javax.swing.JRadioButton tripple_des_button;
    // End of variables declaration//GEN-END:variables
}
