/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import EncryptionAlgorithms.DesEncrypter;
import EncryptionAlgorithms.RSAEncryptor;
import EncryptionAlgorithms.TrippleDes;
import General.Configuration;
import General.Nimbus;
import db.Dbcon;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.security.PublicKey;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Jithinpv
 */
public class SelectAlgorithm extends javax.swing.JFrame {

    int history_id;
    File coverFile;
    String password;

    /**
     * Creates new form SelectAlgorithm
     */
    public SelectAlgorithm() {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        algorith_details.setContentType("text/html");
        algorithmSelected();

    }

    public SelectAlgorithm(int history_id, File coverFile, String password) {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        algorith_details.setContentType("text/html");
        this.history_id = history_id;
        this.coverFile = coverFile;
        this.password = password;
        algorithmSelected();
        Configuration.setIconOnLabel("binary.jpg", main_label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        algorith_details = new javax.swing.JTextPane();
        main_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Algorithm");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 29, 199, 24));

        buttonGroup7.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("DES");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 87, -1, -1));

        buttonGroup7.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Tripple DES");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 87, -1, -1));

        buttonGroup7.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("RSA");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 87, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DES Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 145, 158, -1));

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 547, -1, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 547, -1, -1));

        jScrollPane2.setViewportView(algorith_details);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 170, 556, 366));

        main_label.setText("jLabel3");
        getContentPane().add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 610, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String des = jRadioButton1.getText();
        String tdes = jRadioButton2.getText();
        String rsa = jRadioButton3.getText();
        int id;

        String message = InputContent.message.trim();

        System.out.println("Encrpting text : " + message);
        if (jRadioButton1.isSelected()) {
            id = 1;
            // des
            try {
                String desKey = "0123456789abcdef";
                byte[] keyBytes = DatatypeConverter.parseHexBinary(desKey);
                SecretKeyFactory factory = SecretKeyFactory.getInstance("DES");
                SecretKey key = factory.generateSecret(new DESKeySpec(keyBytes));
                DesEncrypter encrypter = new DesEncrypter(key);

                String encrypted = encrypter.encrypt(message);
                InputContent.message = encrypted;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (jRadioButton2.isSelected()) {
            id = 2;
            //triple des
            try {
                TrippleDes trippleDes = new TrippleDes();
                String encrypted = trippleDes.encrypt(message);
                InputContent.message = encrypted;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            id = 3;
            //rsa
            try {
                if (!RSAEncryptor.areKeysPresent()) {
                    RSAEncryptor.generateKey();
                }

                ObjectInputStream inputStream = null;

                // Encrypt the string using the public key
                inputStream = new ObjectInputStream(new FileInputStream(RSAEncryptor.PUBLIC_KEY_FILE));
                final PublicKey publicKey = (PublicKey) inputStream.readObject();
                InputContent.message = RSAEncryptor.encrypt(message, publicKey);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        System.out.println("message is encryptrd to -------------------- " + InputContent.message);


        Dbcon dbcon = new Dbcon();
        dbcon.update("update tbl_file_process_history set encryption_algorithm_id='" + id + "',encrption_start_time='" + System.currentTimeMillis() + "' where history_id='" + history_id + "'");
        this.dispose();
        Processing processing = new Processing(history_id, coverFile, password, id);
        processing.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void algorithmSelected() {
        Dbcon dbcon = new Dbcon();
        if (jRadioButton1.isSelected()) {
            ResultSet rs = dbcon.select("select * from tbl_encrption_algorithms where algorithm_id=1");
            try {
                if (rs.next()) {
                    algorith_details.setText("<html>" + rs.getString(3) + "</html>");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (jRadioButton2.isSelected()) {
            ResultSet rs = dbcon.select("select * from tbl_encrption_algorithms where algorithm_id=2");
            try {
                if (rs.next()) {
                    algorith_details.setText(rs.getString(3));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            ResultSet rs = dbcon.select("select * from tbl_encrption_algorithms where algorithm_id=3");
            try {
                if (rs.next()) {
                    algorith_details.setText(rs.getString(3));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        InputContent inputContent = new InputContent();
        inputContent.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        algorithmSelected();
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        algorithmSelected();
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        // TODO add your handling code here:
        algorithmSelected();
    }//GEN-LAST:event_jRadioButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SelectAlgorithm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane algorith_details;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel main_label;
    // End of variables declaration//GEN-END:variables
}
